var searchData=
[
  ['wcocojsonsaver',['WCocoJsonSaver',['../classop_1_1_w_coco_json_saver.html',1,'op']]],
  ['wcvmattoopinput',['WCvMatToOpInput',['../classop_1_1_w_cv_mat_to_op_input.html',1,'op']]],
  ['wcvmattoopoutput',['WCvMatToOpOutput',['../classop_1_1_w_cv_mat_to_op_output.html',1,'op']]],
  ['wdatumproducer',['WDatumProducer',['../classop_1_1_w_datum_producer.html',1,'op']]],
  ['webcamreader',['WebcamReader',['../classop_1_1_webcam_reader.html',1,'op']]],
  ['wfacedetector',['WFaceDetector',['../classop_1_1_w_face_detector.html',1,'op']]],
  ['wfacedetectoropencv',['WFaceDetectorOpenCV',['../classop_1_1_w_face_detector_open_c_v.html',1,'op']]],
  ['wfaceextractornet',['WFaceExtractorNet',['../classop_1_1_w_face_extractor_net.html',1,'op']]],
  ['wfacerenderer',['WFaceRenderer',['../classop_1_1_w_face_renderer.html',1,'op']]],
  ['wfacesaver',['WFaceSaver',['../classop_1_1_w_face_saver.html',1,'op']]],
  ['wgui',['WGui',['../classop_1_1_w_gui.html',1,'op']]],
  ['wgui3d',['WGui3D',['../classop_1_1_w_gui3_d.html',1,'op']]],
  ['wguiinfoadder',['WGuiInfoAdder',['../classop_1_1_w_gui_info_adder.html',1,'op']]],
  ['whanddetector',['WHandDetector',['../classop_1_1_w_hand_detector.html',1,'op']]],
  ['whanddetectorfromtxt',['WHandDetectorFromTxt',['../classop_1_1_w_hand_detector_from_txt.html',1,'op']]],
  ['whanddetectortracking',['WHandDetectorTracking',['../classop_1_1_w_hand_detector_tracking.html',1,'op']]],
  ['whanddetectorupdate',['WHandDetectorUpdate',['../classop_1_1_w_hand_detector_update.html',1,'op']]],
  ['whandextractornet',['WHandExtractorNet',['../classop_1_1_w_hand_extractor_net.html',1,'op']]],
  ['whandrenderer',['WHandRenderer',['../classop_1_1_w_hand_renderer.html',1,'op']]],
  ['whandsaver',['WHandSaver',['../classop_1_1_w_hand_saver.html',1,'op']]],
  ['wheatmapsaver',['WHeatMapSaver',['../classop_1_1_w_heat_map_saver.html',1,'op']]],
  ['widgenerator',['WIdGenerator',['../classop_1_1_w_id_generator.html',1,'op']]],
  ['wimagesaver',['WImageSaver',['../classop_1_1_w_image_saver.html',1,'op']]],
  ['wkeeptopnpeople',['WKeepTopNPeople',['../classop_1_1_w_keep_top_n_people.html',1,'op']]],
  ['wkeypointscaler',['WKeypointScaler',['../classop_1_1_w_keypoint_scaler.html',1,'op']]],
  ['wopoutputtocvmat',['WOpOutputToCvMat',['../classop_1_1_w_op_output_to_cv_mat.html',1,'op']]],
  ['worker',['Worker',['../classop_1_1_worker.html',1,'op']]],
  ['workerconsumer',['WorkerConsumer',['../classop_1_1_worker_consumer.html',1,'op']]],
  ['workerproducer',['WorkerProducer',['../classop_1_1_worker_producer.html',1,'op']]],
  ['wpeoplejsonsaver',['WPeopleJsonSaver',['../classop_1_1_w_people_json_saver.html',1,'op']]],
  ['wpersonidextractor',['WPersonIdExtractor',['../classop_1_1_w_person_id_extractor.html',1,'op']]],
  ['wposeextractor',['WPoseExtractor',['../classop_1_1_w_pose_extractor.html',1,'op']]],
  ['wposeextractornet',['WPoseExtractorNet',['../classop_1_1_w_pose_extractor_net.html',1,'op']]],
  ['wposerenderer',['WPoseRenderer',['../classop_1_1_w_pose_renderer.html',1,'op']]],
  ['wposesaver',['WPoseSaver',['../classop_1_1_w_pose_saver.html',1,'op']]],
  ['wposetriangulation',['WPoseTriangulation',['../classop_1_1_w_pose_triangulation.html',1,'op']]],
  ['wqueueassembler',['WQueueAssembler',['../classop_1_1_w_queue_assembler.html',1,'op']]],
  ['wqueueorderer',['WQueueOrderer',['../classop_1_1_w_queue_orderer.html',1,'op']]],
  ['wrapper',['Wrapper',['../classcl_1_1detail_1_1_wrapper.html',1,'cl::detail']]],
  ['wrapper_3c_20cl_5fcommand_5fqueue_20_3e',['Wrapper&lt; cl_command_queue &gt;',['../classcl_1_1detail_1_1_wrapper.html',1,'cl::detail']]],
  ['wrapper_3c_20cl_5fcontext_20_3e',['Wrapper&lt; cl_context &gt;',['../classcl_1_1detail_1_1_wrapper.html',1,'cl::detail']]],
  ['wrapper_3c_20cl_5fdevice_5fid_20_3e',['Wrapper&lt; cl_device_id &gt;',['../classcl_1_1detail_1_1_wrapper_3_01cl__device__id_01_4.html',1,'cl::detail']]],
  ['wrapper_3c_20cl_5fevent_20_3e',['Wrapper&lt; cl_event &gt;',['../classcl_1_1detail_1_1_wrapper.html',1,'cl::detail']]],
  ['wrapper_3c_20cl_5fkernel_20_3e',['Wrapper&lt; cl_kernel &gt;',['../classcl_1_1detail_1_1_wrapper.html',1,'cl::detail']]],
  ['wrapper_3c_20cl_5fmem_20_3e',['Wrapper&lt; cl_mem &gt;',['../classcl_1_1detail_1_1_wrapper.html',1,'cl::detail']]],
  ['wrapper_3c_20cl_5fplatform_5fid_20_3e',['Wrapper&lt; cl_platform_id &gt;',['../classcl_1_1detail_1_1_wrapper.html',1,'cl::detail']]],
  ['wrapper_3c_20cl_5fprogram_20_3e',['Wrapper&lt; cl_program &gt;',['../classcl_1_1detail_1_1_wrapper.html',1,'cl::detail']]],
  ['wrapper_3c_20cl_5fsampler_20_3e',['Wrapper&lt; cl_sampler &gt;',['../classcl_1_1detail_1_1_wrapper.html',1,'cl::detail']]],
  ['wrapperstructextra',['WrapperStructExtra',['../structop_1_1_wrapper_struct_extra.html',1,'op']]],
  ['wrapperstructface',['WrapperStructFace',['../structop_1_1_wrapper_struct_face.html',1,'op']]],
  ['wrapperstructhand',['WrapperStructHand',['../structop_1_1_wrapper_struct_hand.html',1,'op']]],
  ['wrapperstructinput',['WrapperStructInput',['../structop_1_1_wrapper_struct_input.html',1,'op']]],
  ['wrapperstructoutput',['WrapperStructOutput',['../structop_1_1_wrapper_struct_output.html',1,'op']]],
  ['wrapperstructpose',['WrapperStructPose',['../structop_1_1_wrapper_struct_pose.html',1,'op']]],
  ['wrappert',['WrapperT',['../classop_1_1_wrapper_t.html',1,'op']]],
  ['wscaleandsizeextractor',['WScaleAndSizeExtractor',['../classop_1_1_w_scale_and_size_extractor.html',1,'op']]],
  ['wudpsender',['WUdpSender',['../classop_1_1_w_udp_sender.html',1,'op']]],
  ['wvideosaver',['WVideoSaver',['../classop_1_1_w_video_saver.html',1,'op']]]
];
