var namespacecl_1_1detail =
[
    [ "ReferenceHandler", "structcl_1_1detail_1_1_reference_handler.html", null ],
    [ "param_traits", "structcl_1_1detail_1_1param__traits.html", null ],
    [ "GetInfoFunctor0", "structcl_1_1detail_1_1_get_info_functor0.html", "structcl_1_1detail_1_1_get_info_functor0" ],
    [ "GetInfoFunctor1", "structcl_1_1detail_1_1_get_info_functor1.html", "structcl_1_1detail_1_1_get_info_functor1" ],
    [ "ReferenceHandler< cl_device_id >", "structcl_1_1detail_1_1_reference_handler_3_01cl__device__id_01_4.html", null ],
    [ "ReferenceHandler< cl_platform_id >", "structcl_1_1detail_1_1_reference_handler_3_01cl__platform__id_01_4.html", null ],
    [ "ReferenceHandler< cl_context >", "structcl_1_1detail_1_1_reference_handler_3_01cl__context_01_4.html", null ],
    [ "ReferenceHandler< cl_command_queue >", "structcl_1_1detail_1_1_reference_handler_3_01cl__command__queue_01_4.html", null ],
    [ "ReferenceHandler< cl_mem >", "structcl_1_1detail_1_1_reference_handler_3_01cl__mem_01_4.html", null ],
    [ "ReferenceHandler< cl_sampler >", "structcl_1_1detail_1_1_reference_handler_3_01cl__sampler_01_4.html", null ],
    [ "ReferenceHandler< cl_program >", "structcl_1_1detail_1_1_reference_handler_3_01cl__program_01_4.html", null ],
    [ "ReferenceHandler< cl_kernel >", "structcl_1_1detail_1_1_reference_handler_3_01cl__kernel_01_4.html", null ],
    [ "ReferenceHandler< cl_event >", "structcl_1_1detail_1_1_reference_handler_3_01cl__event_01_4.html", null ],
    [ "Wrapper", "classcl_1_1detail_1_1_wrapper.html", "classcl_1_1detail_1_1_wrapper" ],
    [ "Wrapper< cl_device_id >", "classcl_1_1detail_1_1_wrapper_3_01cl__device__id_01_4.html", "classcl_1_1detail_1_1_wrapper_3_01cl__device__id_01_4" ],
    [ "SVMTraitNull", "classcl_1_1detail_1_1_s_v_m_trait_null.html", null ],
    [ "Deleter", "classcl_1_1detail_1_1_deleter.html", "classcl_1_1detail_1_1_deleter" ],
    [ "KernelArgumentHandler", "structcl_1_1detail_1_1_kernel_argument_handler.html", null ],
    [ "KernelArgumentHandler< T, typename std::enable_if<!std::is_base_of< cl::Memory, T >::value >::type >", "structcl_1_1detail_1_1_kernel_argument_handler_3_01_t_00_01typename_01std_1_1enable__if_3_9std_10affa824618af864313998f2e6bcf08f.html", null ],
    [ "KernelArgumentHandler< T, typename std::enable_if< std::is_base_of< cl::Memory, T >::value >::type >", "structcl_1_1detail_1_1_kernel_argument_handler_3_01_t_00_01typename_01std_1_1enable__if_3_01std_cb5bfaca8096193f715a7bbe8a3fa84f.html", null ],
    [ "KernelArgumentHandler< LocalSpaceArg, void >", "structcl_1_1detail_1_1_kernel_argument_handler_3_01_local_space_arg_00_01void_01_4.html", null ],
    [ "KernelArgumentHandler< cl::DeviceCommandQueue, void >", "structcl_1_1detail_1_1_kernel_argument_handler_3_01cl_1_1_device_command_queue_00_01void_01_4.html", null ]
];